### ISSUE TITLE
Box detect group of person

### ISSUE THREAD

**Issue by mrba59** [Accenture/AIR#5]
Hi,
I've runned inference on my eval dataset, the results are really good and i congrat you on that it's really impressive. I just have one question.
The inference detect 15 person on this image , as you can see some box contains more that one person but they are detected as one, maybe there is a parameter taking account group of person ? Is there any chance to return one box for each person ?

![frame22401-idx-7](https://user-images.githubusercontent.com/32193116/157331362-101a042e-5114-4a7d-a34f-2af5ea0f662f.jpg)

**Comment by raghavzns** [comment]
How did you solve it ?

**Comment by mrba59** [comment]
choosing nms_mode: enclose and playing with the nms_threshold

**Comment by Hyper5phere** [comment]
You can also try nms_mode: "argmax" for more conventional bounding box postprocessing. It tries to delineate each person separately unlike the "enclose" method, which uses the MOB algorithm I designed for SAR purposes. Though you might need to run the [convert-model.sh](https://github.com/Accenture/AIR/blob/master/convert-model.sh) script again with a different BBA (bounding box aggregation) mode.

Nice to know the model works so well on football fields as well 😄
