### ISSUE TITLE
Dataset unavailable

### ISSUE THREAD

**Issue by lodm94** [Accenture/AIR#8]
Hi, nice work! Unfortunately i can't reach out the HERIDAL download page. 
If i try from here:
http://ipsar.fesb.unist.hr/HERIDAL%20database.html
It prompts an error.

Is there any chance you have an offline dump you can share with me somehow?

Thanks

**Comment by Hyper5phere** [comment]
This is not really an issue with the software provided in this repository, so I'm closing it after this comment. For me that link is working anyhow, but in case of further issues I suggest you contact the people hosting that website.

Also, if you want to work with my slightly modified version of the HERIDAL dataset (data and labels are the same, just in different, easier format), you should be able to download it from https://zenodo.org/record/5662351

The main benefit is that it can be used with the AIR detector out of the box (unlike the original data set).
